server:
  http_listen_port: 9080

clients:
  - url: http://34.47.69.9:3100/loki/api/v1/push

scrape_configs:
  - job_name: user-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: user-service
          __path__: /logs/*.log